# Generated by Django 2.0.4 on 2018-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180507_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='value',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
