# Generated by Django 2.0.4 on 2018-06-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts2',
        ),
    ]
