# Generated by Django 2.0.4 on 2018-06-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_posts2'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.CharField(default='meanwhile', max_length=200),
            preserve_default=False,
        ),
    ]
